import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { ExternalLink, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Link } from 'react-router-dom';

interface PortfolioPreviewProps {
    open: boolean;
    onClose: () => void;
    data: { html: string; id?: string } | null;
    title?: string;
}

export function PortfolioPreview({ open, onClose, data, title = "Portfolio Preview" }: PortfolioPreviewProps) {
    const [isContentVisible, setIsContentVisible] = useState(false);

    useEffect(() => {
        if (open) {
            const timer = setTimeout(() => {
                setIsContentVisible(true);
            }, 200);
            return () => clearTimeout(timer);
        } else {
            setIsContentVisible(false);
        }
    }, [open]);

    const handleDownload = async () => {
        if (!data?.html) return;

        try {
            const JSZip = (await import("jszip")).default;
            const { saveAs } = await import("file-saver");

            const zip = new JSZip();
            zip.file("index.html", data.html);

            // Generate a README
            const readme = `
# Portfolio Website
Generated by AI Portfolio Architect

## How to use
1. Unzip this folder.
2. Open 'index.html' in your browser.
3. All libraries (GSAP, Lenis, etc.) are loaded via CDN, so an internet connection is required.

## Customization
You can edit 'index.html' directly to change images, text, or styles.
            `;
            zip.file("README.md", readme.trim());

            const content = await zip.generateAsync({ type: "blob" });
            saveAs(content, `${title.replace(/\s+/g, '-').toLowerCase()}-portfolio.zip`);

        } catch (error) {
            console.error("Download failed:", error);
            // You might want to import toast here if you want to show error to user
        }
    };

    if (!data) return null;

    // Inject safety script to prevent redirects in existing portfolios
    const safeHtml = data?.html ? data.html + `
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                document.querySelectorAll('a').forEach(el => {
                    const href = el.getAttribute('href');
                    if (href && (href === '/' || href === '/home' || href === 'index.html')) {
                        el.setAttribute('href', '#home');
                        el.addEventListener('click', (e) => {
                            e.preventDefault();
                            const home = document.getElementById('home');
                            if(home) home.scrollIntoView({ behavior: 'smooth' });
                        });
                    }
                });
            });
        </script>
    ` : "";

    return (
        <Dialog open={open} onOpenChange={onClose}>
            <DialogContent className="max-w-7xl w-[95vw] h-[90vh] flex flex-col p-0 gap-0 duration-500 shadow-2xl border-none ring-1 ring-gray-200/50 [&>button]:hidden">
                <DialogHeader className="p-3 md:p-4 border-b flex flex-row items-center justify-between space-y-0 bg-muted/30 shrink-0">
                    <div className="flex items-center gap-2 overflow-hidden">
                        <Button variant="ghost" size="icon" onClick={onClose} className="rounded-full hover:scale-110 transition-transform duration-200 shrink-0">
                            <X className="w-5 h-5" />
                        </Button>
                        <DialogTitle className="truncate font-semibold text-sm md:text-lg">{title}</DialogTitle>
                    </div>
                    <div className="flex items-center gap-1 md:gap-2 shrink-0">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleDownload}
                            className="hover:scale-105 transition-transform duration-200"
                            title="Download ZIP"
                        >
                            <span className="hidden sm:inline mr-2">Download ZIP</span>
                            <ExternalLink className="w-4 h-4 rotate-180" />
                        </Button>

                        {/* Only show 'Open Full Site' if we have an ID */}
                        {data.id && (
                            <Link to={`/dashboard/portfolios/${data.id}`}>
                                <Button variant="default" size="sm" className="hover:scale-105 transition-transform duration-200" title="Open Full Site">
                                    <ExternalLink className="w-4 h-4 sm:mr-2" />
                                    <span className="hidden sm:inline">Open Full Site</span>
                                </Button>
                            </Link>
                        )}
                    </div>
                </DialogHeader>

                <div className="flex-1 overflow-hidden bg-gray-100 relative">
                    {/* Overlay for interaction blocking if needed, but for preview we want scroll */}
                    <div
                        className={`w-full h-full transition-opacity duration-500 ease-in-out ${isContentVisible ? 'opacity-100' : 'opacity-0'}`}
                    >
                        <iframe
                            title="Portfolio Preview"
                            srcDoc={safeHtml}
                            className="w-full h-full border-0"
                            sandbox="allow-scripts allow-same-origin"
                        />
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
